name: Basic

on:
  push:
    branches:  
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4
      - name: Setup
        run: go get -d ./...
      - name: Tests
        run: go test -v ./...